### PR TITLE
Adding ARCHIVE DESTINATION to fix CMake error

### PR DESCRIPTION
**Pull request by matthew-olson-intel**

### CODE REVIEW

**Comment by athre0z** [comment]
Thanks for the PR! Interesting. In Zydis, [we have this](https://github.com/zyantific/zydis/blob/871c40c585271227e3233e828005ada5be8ace4a/CMakeLists.txt#L246-L250):

```cmake
install(TARGETS "Zydis"
    EXPORT "zydis-targets"
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
```
I think we should probably also add `LIBRARY DESTINATION` here for consistency. I suspect that things will otherwise break under these CMake versions if a shared library is built. No need for `RUNTIME DESTINATION` though -- Zycore doesn't have any binaries and I don't expect it to ever gain any.

**Comment by matthew-olson-intel** [comment]
Good idea-- added that, too.

**Review by athre0z — APPROVED** [review]
Thanks, LGTM!

**Comment by Tachi107** [comment]
Leaving this for future reference: in CMake 3.14, these various `<TYPE> DESTINATION <DIRECTORY>` fields are implied by default, so they can be removed to make the code a bit cleaner :)

**Pull request merged**
