### PR TITLE
Fix build-system to better work with vcpkg

### PR DESCRIPTION
**Pull request by r4ve1**
1. Copy cmake's config files to a `zycore` subfolder under `lib/cmake` makes no sense and will harm the integration with vcpkg.
2. When building dynamic libs under Windows, `.dll` file won't be copied to install path.

### CODE REVIEW

**Comment by r4ve1** [comment]
And please grant a tag for this commit, I'm porting this repo to vcpkg 😸

**Comment by flobernd** [comment]
Not sure about this one.

In `Zydis` it's done the same way as part of a previous fix: https://github.com/zyantific/zydis/commit/8080ae55edf2e248f525ed2c8fea35cf3521d5cd.

I sadly don't know which way is correct. We have to make sure "regular" installation does not break and we definitely want to make sure it's consistent in both modules.

**Comment by flobernd** [comment]
@Tachi107 you contributed a lot of CMake related changes in the past. What do you think? 🙂

**Comment by athre0z** [comment]
At least on Debian and Arch, having a sub-directory per library appears to be the common case:

### Debian

```console
$ ls -la /usr/lib/aarch64-linux-gnu/cmake
total 164
drwxr-xr-x   8 root root   4096 Oct 12 15:46 .
drwxr-xr-x 139 root root 131072 Oct 12 15:46 ..
drwxr-xr-x   2 root root   4096 Sep 20 11:58 Boost-1.74.0
-rw-r--r--   1 root root   3434 Aug 28 11:13 BoostDetectToolset-1.74.0.cmake
drwxr-xr-x   2 root root   4096 Sep 20 11:58 boost_headers-1.74.0
drwxr-xr-x   2 root root   4096 Sep 27 12:19 expat-2.4.9
drwxr-xr-x   2 root root   4096 Sep 20 11:58 xsimd
drwxr-xr-x   2 root root   4096 Oct 12 15:46 zycore
drwxr-xr-x   2 root root   4096 Oct 12 15:46 zydis
```

### Arch

```console
# ls -lha /usr/lib/cmake
total 256K
drwxr-xr-x 1 root root 4.0K Oct 12 13:56 .
drwxr-xr-x 1 root root  20K Oct 12 13:56 ..
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 Boost-1.80.0
-rw-r--r-- 1 root root 3.6K Sep 19 22:28 BoostDetectToolset-1.80.0.cmake
drwxr-xr-x 1 root root 4.0K Oct 12 13:52 DBus1
drwxr-xr-x 2 root root 4.0K Sep  4 00:04 Gpgmepp
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_atomic-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_chrono-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_container-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_context-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_contract-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_coroutine-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_date_time-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_exception-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_fiber-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_filesystem-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_graph-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_graph_parallel-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_headers-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_iostreams-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_json-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_locale-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_log-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_log_setup-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_math_c99-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_math_c99f-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_math_c99l-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_math_tr1-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_math_tr1f-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_math_tr1l-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_mpi-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_mpi_python-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_nowide-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_numpy-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_prg_exec_monitor-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_program_options-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_python-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_random-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_regex-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_serialization-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_stacktrace_addr2line-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_stacktrace_basic-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_stacktrace_noop-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_system-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_test_exec_monitor-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_thread-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_timer-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_type_erasure-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_unit_test_framework-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_wave-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:55 boost_wserialization-1.80.0
drwxr-xr-x 2 root root 4.0K Oct 12 13:56 expat-2.4.9
drwxr-xr-x 2 root root 4.0K Sep  4 00:04 json-c
drwxr-xr-x 2 root root 4.0K Sep  4 00:04 libevent
drwxr-xr-x 2 root root 4.0K Sep  4 00:04 libxml2
drwxr-xr-x 2 root root 4.0K Oct 12 13:56 xsimd
drwxr-xr-x 2 root root 4.0K Sep  4 00:04 zstd
```

**Comment by Tachi107** [comment]
> 1. Copy cmake's config files to a `zycore` subfolder under `lib/cmake` makes no sense and will harm the integration with vcpkg.

From [CMake's documentation](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure), `<prefix>/(lib/<arch>|lib*|share)/cmake/<name>*/` is also always checked. Why does it create issues with vcpkg?

**Comment by r4ve1** [comment]
> 1. Copy cmake's config files to a zycore subfolder under lib/cmake makes no sense and will harm the integration with vcpkg.

I issued this because I'm currently porting `zycore` to vcpkg and when integrating vcpkg with CMake, `find_package` won't search for config file in subfolders under `[vcpkg_root]/installed/share/zycore/*`, but there is a way to fix this in vcpkg's config file, I'll do it that way.

> 2. When building dynamic libs under Windows, .dll file won't be copied to install path.

However this should be fixed. If you build and install this library statically on Windows, you will find `.dll` file won't be installed, because according to [CMake's document](https://cmake.org/cmake/help/latest/command/install.html), `.dll` files belong to the `RUNTIME` artifacts.

**Comment by Tachi107** [comment]
> However this should be fixed. If you build and install this library statically on Windows, you will find .dll file won't be installed, because according to CMake's document, .dll files belong to the RUNTIME artifacts

Sure. But won't removing the LIBRARY line cause issues when installing shared libraries?

**Comment by r4ve1** [comment]
It won't, tested on both Linux and Windows.

**Comment by athre0z** [comment]
I can confirm that it does not break anything on CMake 3.23 to do it like this, but I'd still leave the `LIBRARY` line in there. We've had issues with this before, see:

https://github.com/zyantific/zycore-c/issues/46
https://github.com/zyantific/zycore-c/pull/47

Quoting @Tachi107 from [this post](https://github.com/zyantific/zycore-c/pull/47#issuecomment-1206329061):

> Leaving this for future reference: in CMake 3.14, these various <TYPE> DESTINATION <DIRECTORY> fields are implied by default, so they can be removed to make the code a bit cleaner :)

In other words: removing this is fine on CMake >= 3.14, but will probably break on older versions. Our minimum supported CMake version is currently 3.9. CMake is a vicious piece of software.. 😅

**Comment by flobernd** [comment]
Agreed. Let's keep both `LIBRARY` and `RUNTIME` if that works.

**Comment by athre0z** [comment]
> nd let's do the same changes for the zydis module as well.

Zydis [already has this line](https://github.com/zyantific/zydis/blob/master/CMakeLists.txt#L252) because it also install binaries. I just didn't realize that CMake had the glorious idea of adding a platform specific exception for Windows to put `.dll`s into the executable directory, which is [why we didn't add it in zycore](https://github.com/zyantific/zycore-c/pull/47#issuecomment-1179422046).

**Comment by flobernd** [comment]
#cmake

**Comment by r4ve1** [comment]
Added

**Review by flobernd — APPROVED** [review]
LGTM! Thanks.

@athre0z I guess it makes sense to bump the version (patch) one more time and update the submodule in Zydis. We can release a new v4 RC afterwards (or even the major version).

@r4ve1 I suggest to wait for 1-3 days until we release Zydis v4 to have the latest version available on vcpkg right away.

**Comment by r4ve1** [comment]
Of course. My port of Zycore is still not accepted by vcpkg's maintainers, so a few days waiting to the new release of Zydis won't harm anything 😄
By the way, Zydis & Zycore are amazing, thanks for your great work 👍

**Comment by Tachi107** [comment]
https://github.com/zyantific/zycore-c/pull/56#issuecomment-1276685744

This comment expressed all my concerns perfectly :)

Should an `ARCHIVE` section also be added? [CMake's documentation](https://cmake.org/cmake/help/latest/command/install.html#targets) says that static libraries get installed there

**Comment by flobernd** [comment]
@Tachi107 

> Should an ARCHIVE section also be added?

Seems like `ARCHIVE` is already specified 🙂

**Comment by Tachi107** [comment]
Oops, right 😅

**Review by athre0z — APPROVED** [review]
LGTM!

> I guess it makes sense to bump the version (patch) one more time and update the submodule in Zydis. We can release a new v4 RC afterwards (or even the major version).

Yeah, let's do that!

**Pull request merged**
