### PR TITLE
Add CI workflow

### PR DESCRIPTION
**Pull request by flobernd**

### CODE REVIEW

**Review by athre0z — APPROVED** [review]
LGTM, thanks for taking the time to finally do that! Not sure if we really need 32 bit builds for Linux -- there's probably less than 1000 users on the planet who still actively use that outside of Wine (which also started moving away from it by implementing WoW64), but I guess it doesn't hurt. If it ever starts making problems, I'd opt for just dropping it.

**Comment by flobernd** [comment]
Would love to have CI for ICC and Borland as well to cover all our supported compilers, but as they are commercial, we are probably out of luck here.

**Comment by athre0z** [comment]
Borland C is largely dead and ICC [is now Clang with a forked LLVM backend](https://www.intel.com/content/www/us/en/developer/articles/technical/adoption-of-llvm-complete-icx.html), so the current selection should be pretty good.

**Comment by flobernd** [comment]
> ICC is now Clang with a forked LLVM backend

Oh nice. Did not know about that yet.

**Pull request merged**
